version: '3.7'

networks:
  elk:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: "${ELASTICSEARCH_CONTAINER}"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    container_name: "${LOGSTASH_CONTAINER}"
    ports:
      - "5044:5044"
      - "9600:9600"
      - "6000:6000"
    networks:
      - elk
    volumes:
      - ./data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: "${KIBANA_CONTAINER}"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    image: nginx
    container_name: "${NGINX_CONTAINER}"
    ports:
      - "80:80"
      - "3001:3001"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/www:/nginx/www
    networks:
      - elk
    depends_on:
      - logstash
