version: '3.2'

services:

  nginx:
    image: nginx
    container_name: "${NGINX_CONTAINER_NAME}"
    ports:
      - "80:80"
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./content:/nginx