version: '3.7'

volumes:
  postgres:

networks:
  learn-network:

services:
  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: "${POSTGRES_CONTAINER}"
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
    volumes:
      - postgres:/data/postgres
    networks:
      - learn-network