version: '3.7'

networks:
  learn-network:
    driver: bridge

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "learn"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - learn-network