version: '3.7'

networks:
  learn-network:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: "${NGINX_CONTAINER}"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/www:/nginx/www
    networks:
      - learn-network