version: '3.7'

networks:
  learn-network:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/remote-debugging-app.dockerfile
    image: learn-rba
    container_name: "${APP_CONTAINER}"
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - learn-network